name: Gut Rebuild Notifications
on:
  schedule:
    - cron: '30 5 * * *'
    - cron: '0 6 * * *'
    - cron: '0 9 * * *'
    - cron: '30 11 * * *'
    - cron: '30 14 * * *'
    - cron: '30 17 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          HOUR=$(TZ='Europe/Prague' date '+%H')
          MIN=$(TZ='Europe/Prague' date '+%M')
          
          send() {
            curl -s -F "token=a9wxwbgdo7qxte9rz2f8wp5jkdcgew" \
              -F "user=uzw2pfxcjohf159w8jir29u4a5f3s5" \
              -F "title=$1" -F "message=$2" \
              -F "priority=1" -F "sound=persistent" -F "retry=60" -F "expire=600" \
              https://api.pushover.net/1/messages.json
          }
          
          case "${HOUR}:${MIN}" in
            06:3*) send "NALACNO -- 6:30" "L-Glutamin 5g do vody
          Probiotika 1 kapsle
          Vlazna voda s citronem 300ml" ;;
            07:0*) send "SNIDANE -- 7:00" "Vitamin D3+K2 + B-komplex + Omega-3
          Priprav si snidani
          Zacni pit vodu - cil 500ml do 9:00" ;;
            10:0*) send "DOPOLEDNI SVACINA -- 10:00" "Matcha z termosky
          Kreatin 5g do vody
          Sezrat svacinu
          Voda 500ml do 12:00" ;;
            12:3*) send "OBED -- 12:30" "Omega-3 1g + Travici enzymy
          Obed z jidelnicku
          Voda + hermankovy caj 750ml do 15:00" ;;
            15:3*) send "SHAKE + SVACINA -- 15:30" "DIY gainer: whey 30g + palatinose 50g + banan
          L-Glutamin 5g v shakeru
          Nebo svacina z jidelnicku" ;;
            18:3*) send "VECERE -- 18:30" "Kombucha 150ml + Zinek 25mg
          Vecere z jidelnicku
          Zazvorovy caj 250ml" ;;
            20:0*|21:0*) send "PRED SPANIM -- 21:00" "Shake #2: whey 30g + palatinose 40g + mleko
          Horcik 400mg + Kolagen 10g
          Posledni voda 300ml" ;;
          esac
